# Generated by Django 4.2.7 on 2023-11-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='P_CHOICES',
            field=models.CharField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=5),
        ),
    ]
