# Generated by Django 4.2.7 on 2023-11-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_p_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='P_CHOICES',
        ),
        migrations.AddField(
            model_name='task',
            name='CHOICES',
            field=models.ImageField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], upload_to=''),
        ),
    ]
