# Generated by Django 4.2.7 on 2023-11-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_p_choices_task_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='CHOICES',
        ),
        migrations.AddField(
            model_name='task',
            name='priority_choice',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
            preserve_default=False,
        ),
    ]
